# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from versify import schemas  # noqa: F401


class IdentityProvider(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An identity provider for a user.
    """


    class MetaOapg:
        required = {
            "provider_type",
            "provider_subject",
        }
        
        class properties:
            provider_subject = schemas.StrSchema
            provider_type = schemas.StrSchema
            __annotations__ = {
                "provider_subject": provider_subject,
                "provider_type": provider_type,
            }
    
    provider_type: MetaOapg.properties.provider_type
    provider_subject: MetaOapg.properties.provider_subject
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider_subject"]) -> MetaOapg.properties.provider_subject: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provider_type"]) -> MetaOapg.properties.provider_type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["provider_subject", "provider_type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider_subject"]) -> MetaOapg.properties.provider_subject: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provider_type"]) -> MetaOapg.properties.provider_type: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["provider_subject", "provider_type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        provider_type: typing.Union[MetaOapg.properties.provider_type, str, ],
        provider_subject: typing.Union[MetaOapg.properties.provider_subject, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IdentityProvider':
        return super().__new__(
            cls,
            *_args,
            provider_type=provider_type,
            provider_subject=provider_subject,
            _configuration=_configuration,
            **kwargs,
        )
