# coding: utf-8

# flake8: noqa

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from versify.api_client import ApiClient

# import Configuration
from versify.configuration import Configuration

# import exceptions
from versify.exceptions import OpenApiException
from versify.exceptions import ApiAttributeError
from versify.exceptions import ApiTypeError
from versify.exceptions import ApiValueError
from versify.exceptions import ApiKeyError
from versify.exceptions import ApiException
