# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import versify
from versify.model.account_metrics import AccountMetrics
from versify import configuration


class TestAccountMetrics(unittest.TestCase):
    """AccountMetrics unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
