# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import versify
from versify.model.collection_create import CollectionCreate
from versify import configuration


class TestCollectionCreate(unittest.TestCase):
    """CollectionCreate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
