# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import versify
from versify.model.trigger_config import TriggerConfig
from versify import configuration


class TestTriggerConfig(unittest.TestCase):
    """TriggerConfig unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
