openapi: 3.0.0

info:
  description: |
    The Versify API is organized around REST. 
    Our API has predictable resource-oriented URLs, accepts JSON request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
  version: 1.0.0
  title: Versify API Reference
  contact:
    email: support@versifylabs.com

host: "https://versifylabs.com"

servers:
  - description: Versify Production API
    url: https://api.versifylabs.com/v1
  - description: Versify Development API
    url: https://api-dev.versifylabs.com

tags:
  - name: products
    description: Operations available to regular products

paths:
  /products:
    get:
      summary: List products
      description: |
        Returns a list of your products. 
        The products are returned sorted by creation date, with the most recently created products appearing first.
      operationId: listProducts
      tags:
        - products
      parameters:
        $ref: "#/components/schemas/ProductListRequestParameters"
      responses:
        "200":
          description: |
            A dictionary with a data property that contains an array of up to page_size objects. 
            Each entry in the array is a separate object. 
            If no more objects are available, the resulting array will be empty. This request should never raise an error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductList"
        "400":
          name: Bad Request
          description: The request was unacceptable, often due to missing a required parameter.

components:
  schemas:
    ListRequestParameters:
      - in: query
        name: page_num
        description: A cursor for use in pagination.
        required: false
        schema:
          type: string
      - in: query
        name: page_size
        description: number of products to return
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
          default: 25
    ProductListRequestParameters:
      - in: query
        name: collection
        description: Only return products for the collection specified by this id.
        example: publicAPI
        required: false
        schema:
          type: string
      - in: query
        name: page_num
        description: A cursor for use in pagination.
        required: false
        schema:
          type: string
      - in: query
        name: page_size
        description: number of products to return
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
          default: 25
    ProductList:
      type: object
      properties:
        object:
          type: string
          example: list
        url:
          type: string
          example: "/v1/products"
        has_more:
          type: boolean
          example: false
        data:
          type: array
          items:
            $ref: "#/components/schemas/Product"
    Product:
      type: object
      required:
        - id
        - object
        - description
        - name
        - image
      properties:
        id:
          type: string
          example: demo
          description: The id of the Product. Assigned when added.
        object:
          type: string
          example: product
          description: The type of object.
        description:
          type: string
          example: This is just a test product
          description: The description of the product.
        name:
          type: string
          example: Monkeyball
          description: The name of the product.
        image:
          type: string
          example: https://cdn.versifylabs.com/products/123
          description: The url of the image of the product.
