# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_collections.post import CreateCollectionV2CollectionsPost
from versify.paths.v2_collections.post import CreateCollectionV2CollectionsPost0
from versify.paths.v2_collections_collection_id.delete import DeleteCollectionV2CollectionsCollectionIdDelete
from versify.paths.v2_collections_collection_id.delete import DeleteCollectionV2CollectionsCollectionIdDelete0
from versify.paths.v2_collections_collection_id.get import GetCollectionV2CollectionsCollectionIdGet
from versify.paths.v2_collections_collection_id.get import GetCollectionV2CollectionsCollectionIdGet0
from versify.paths.v2_collections.get import ListCollectionsV2CollectionsGet
from versify.paths.v2_collections.get import ListCollectionsV2CollectionsGet0
from versify.paths.v2_collections_search.post import SearchCollectionsV2CollectionsSearchPost
from versify.paths.v2_collections_search.post import SearchCollectionsV2CollectionsSearchPost0
from versify.paths.v2_collections_collection_id.put import UpdateCollectionV2CollectionsCollectionIdPut
from versify.paths.v2_collections_collection_id.put import UpdateCollectionV2CollectionsCollectionIdPut0


class CollectionsApi(
    CreateCollectionV2CollectionsPost,
    CreateCollectionV2CollectionsPost0,
    DeleteCollectionV2CollectionsCollectionIdDelete,
    DeleteCollectionV2CollectionsCollectionIdDelete0,
    GetCollectionV2CollectionsCollectionIdGet,
    GetCollectionV2CollectionsCollectionIdGet0,
    ListCollectionsV2CollectionsGet,
    ListCollectionsV2CollectionsGet0,
    SearchCollectionsV2CollectionsSearchPost,
    SearchCollectionsV2CollectionsSearchPost0,
    UpdateCollectionV2CollectionsCollectionIdPut,
    UpdateCollectionV2CollectionsCollectionIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
