# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_events.post import CreateEventV2EventsPost
from versify.paths.v2_events.post import CreateEventV2EventsPost0
from versify.paths.v2_events_event_id.delete import DeleteEventV2EventsEventIdDelete
from versify.paths.v2_events_event_id.delete import DeleteEventV2EventsEventIdDelete0
from versify.paths.v2_events_event_id.get import GetEventV2EventsEventIdGet
from versify.paths.v2_events_event_id.get import GetEventV2EventsEventIdGet0
from versify.paths.v2_events.get import ListEventsV2EventsGet
from versify.paths.v2_events.get import ListEventsV2EventsGet0
from versify.paths.v2_events_search.post import SearchEventsV2EventsSearchPost
from versify.paths.v2_events_search.post import SearchEventsV2EventsSearchPost0
from versify.paths.v2_events_event_id.put import UpdateEventV2EventsEventIdPut
from versify.paths.v2_events_event_id.put import UpdateEventV2EventsEventIdPut0


class EventsApi(
    CreateEventV2EventsPost,
    CreateEventV2EventsPost0,
    DeleteEventV2EventsEventIdDelete,
    DeleteEventV2EventsEventIdDelete0,
    GetEventV2EventsEventIdGet,
    GetEventV2EventsEventIdGet0,
    ListEventsV2EventsGet,
    ListEventsV2EventsGet0,
    SearchEventsV2EventsSearchPost,
    SearchEventsV2EventsSearchPost0,
    UpdateEventV2EventsEventIdPut,
    UpdateEventV2EventsEventIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
