# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_journeys.post import CreateJourneyV2JourneysPost
from versify.paths.v2_journeys.post import CreateJourneyV2JourneysPost0
from versify.paths.v2_journeys_journey_id.delete import DeleteJourneyV2JourneysJourneyIdDelete
from versify.paths.v2_journeys_journey_id.delete import DeleteJourneyV2JourneysJourneyIdDelete0
from versify.paths.v2_journeys_journey_id.get import GetJourneyV2JourneysJourneyIdGet
from versify.paths.v2_journeys_journey_id.get import GetJourneyV2JourneysJourneyIdGet0
from versify.paths.v2_journeys.get import ListJourneysV2JourneysGet
from versify.paths.v2_journeys.get import ListJourneysV2JourneysGet0
from versify.paths.v2_journeys_search.post import SearchJourneysV2JourneysSearchPost
from versify.paths.v2_journeys_search.post import SearchJourneysV2JourneysSearchPost0
from versify.paths.v2_journeys_journey_id.put import UpdateJourneyV2JourneysJourneyIdPut
from versify.paths.v2_journeys_journey_id.put import UpdateJourneyV2JourneysJourneyIdPut0


class JourneysApi(
    CreateJourneyV2JourneysPost,
    CreateJourneyV2JourneysPost0,
    DeleteJourneyV2JourneysJourneyIdDelete,
    DeleteJourneyV2JourneysJourneyIdDelete0,
    GetJourneyV2JourneysJourneyIdGet,
    GetJourneyV2JourneysJourneyIdGet0,
    ListJourneysV2JourneysGet,
    ListJourneysV2JourneysGet0,
    SearchJourneysV2JourneysSearchPost,
    SearchJourneysV2JourneysSearchPost0,
    UpdateJourneyV2JourneysJourneyIdPut,
    UpdateJourneyV2JourneysJourneyIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
