org: versify
app: versify
service: poc-service

frameworkVersion: ">=2.24.0"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    restApiId: ${ssm:/versify/services/api/id}
    restApiRootResourceId: ${ssm:/versify/services/api/root/resource/id}
  environment:
    ENVIRONMENT: ${opt:stage, 'dev'}
    LOG_LEVEL: INFO
    MONGO_DB_USER: admin
    MONGO_DB_PASS: SECRET
    MONGO_DB_NAME: EventDB
    MONGO_DB_URL: versify.y5nxv.mongodb.net
    MONGO_COLLECTION_NAME: Events
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    POWERTOOLS_LOGGER_LOG_EVENT: true
    POWERTOOLS_METRICS_NAMESPACE: versify
    POWERTOOLS_SERVICE_NAME: poc-service
    POWERTOOLS_TRACE_DISABLED: false
  layers:
    - ${ssm:/versify/services/versify/layer/arn}
    - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPython:11
  runtime: python3.9
  tracing:
    lambda: true

functions:
  API-CreateEvent:
    handler: src.api.handler
    name: PocService-API-CreateEvent
    events:
      - http:
          method: post
          path: /poc/v1/events
          operationId: CreateEvent
          cors: true
