org: versify
app: versify
service: integration-service

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    restApiId: ${ssm:/versify/services/api/id}
    restApiRootResourceId: ${ssm:/versify/services/api/root/resource/id}
    restApiResources:
      /account: ${ssm:/versify/services/account/api/resource/id}
      /admin: ${ssm:/versify/services/admin/api/resource/id}
      /backend: ${ssm:/versify/services/backend/api/resource/id}
  environment:
    ENVIRONMENT: ${opt:stage, 'dev'}
    LOG_LEVEL: INFO
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    POWERTOOLS_LOGGER_LOG_EVENT: true
    POWERTOOLS_METRICS_NAMESPACE: versify
    POWERTOOLS_SERVICE_NAME: integration-service
    POWERTOOLS_TRACE_DISABLED: false
    SECRET_NAME: /versify/platform/secret
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:/versify/platform/secret*"
  layers:
    - ${ssm:/versify/services/versify/layer/arn}
    - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPython:11
  runtime: python3.9
  tracing:
    lambda: true

functions:
  API-Auth0-GetOrganization:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-GetOrganization
    events:
      - http:
          method: get
          path: /admin/integrations/auth0/organizations/{id}
          operationId: GetOrganization
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
      - http:
          method: get
          path: /backend/organizations/{id}
          operationId: GetOrganization
          authorizer:
            type: aws_iam
          request:
            parameters:
              paths:
                id: true
  API-Auth0-UpdateOrganization:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-UpdateOrganization
    events:
      - http:
          method: put
          path: /admin/integrations/auth0/organizations/{id}
          operationId: UpdateOrganization
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
  API-Auth0-CreateOrganizationInvitation:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-CreateOrganizationInvitation
    events:
      - http:
          method: post
          path: /admin/integrations/auth0/organizations/{id}/invitations
          operationId: CreateOrganizationInvitation
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
  API-Auth0-ListOrganizationInvitations:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-ListOrganizationInvitations
    events:
      - http:
          method: get
          path: /admin/integrations/auth0/organizations/{id}/invitations
          operationId: ListOrganizationInvitations
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
  API-Auth0-ListOrganizationMembers:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-ListOrganizationMembers
    events:
      - http:
          method: get
          path: /admin/integrations/auth0/organizations/{id}/members
          operationId: ListOrganizationMembers
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
  API-Auth0-ListOrganizationMemberRoles:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-ListOrganizationMemberRoles
    events:
      - http:
          method: get
          path: /admin/integrations/auth0/organizations/{id}/members/{user_id}/roles
          operationId: ListOrganizationMemberRoles
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/admin/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
                Organization: true
              paths:
                id: true
                user_id: true
  API-Auth0-ListUserOrganizations:
    handler: src.api.handler
    name: IntegrationService-API-Auth0-ListUserOrganizations
    events:
      - http:
          method: get
          path: /account/integrations/auth0/users/{id}/organizations
          operationId: ListUserOrganizations
          authorizer:
            type: REQUEST
            authorizerId: ${ssm:/versify/services/account/api/authorizer/id}
          cors:
            origin: "*"
            headers:
              - Authorization
              - Organization
              - Content-Type
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  # API-Stripe-CreateBillingSession:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-CreateBillingSession
  # API-Stripe-GetCustomer:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-GetCustomer
  # API-Stripe-ListInvoices:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-ListInvoices
  # API-Stripe-ListSubscriptions:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-ListSubscriptions
  # API-StripeConnect-CreateAccountSession:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-CreateAccountSession
  # API-StripeConnect-CreateCheckoutSession:
  #   handler: src.api.handler
  #   name: IntegrationService-API-Stripe-CreateCheckoutSession
