org: versify
app: versify
service: chain-service

frameworkVersion: ">=2.24.0"

plugins:
  - serverless-python-requirements

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    restApiId:
      "Fn::ImportValue": VersifyApiId
    restApiRootResourceId:
      "Fn::ImportValue": VersifyApiRootResourceId
  environment:
    ENVIRONMENT: ${opt:stage, 'dev'}
    LOG_LEVEL: INFO
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    POWERTOOLS_LOGGER_LOG_EVENT: true
    POWERTOOLS_METRICS_NAMESPACE: versify
    POWERTOOLS_SERVICE_NAME: chain-service
    POWERTOOLS_TRACE_DISABLED: false
    SECRET_NAME: /versify/platform/secret
  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:Invoke
      Resource:
        - "arn:aws:execute-api:us-east-1:*:*/*/*/*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:/versify/platform/secret*"
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::cdn.versifylabs.com"
        - "arn:aws:s3:::cdn.versifylabs.com/*"
        - "arn:aws:s3:::cdn-dev.versifylabs.com"
        - "arn:aws:s3:::cdn-dev.versifylabs.com/*"
  layers:
    - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPython:11
  runtime: python3.9
  timeout: 30
  tracing:
    lambda: true

functions:
  DeployContract:
    handler: src.handlers.deploy_contract.handler
    name: ChainService-DeployContract
    maximumRetryAttempts: 0
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/versify/bus/arn}
          pattern:
            source:
              - versify
            detail-type:
              - collection.created
  MintToken:
    handler: src.handlers.mint_token.handler
    name: ChainService-MintToken
    maximumRetryAttempts: 0
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/versify/bus/arn}
          pattern:
            source:
              - versify
            detail-type:
              - mint.fulfilled
  UpdateTransaction:
    handler: src.handlers.update_transaction.handler
    name: ChainService-UpdateTransaction
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/partner/bus/arn}
          pattern:
            source:
              - tatum
            detail-type:
              - transaction.created
  UpdateMetadata:
    handler: src.handlers.update_metadata.handler
    name: ChainService-UpdateMetadata
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/versify/bus/arn}
          pattern:
            source:
              - versify
            detail-type:
              - product.created
              - product.updated
