# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_assets.post import CreateAssetV2AssetsPost
from versify.paths.v2_assets.post import CreateAssetV2AssetsPost0
from versify.paths.v2_assets_asset_id.delete import DeleteAssetV2AssetsAssetIdDelete
from versify.paths.v2_assets_asset_id.delete import DeleteAssetV2AssetsAssetIdDelete0
from versify.paths.v2_assets_asset_id.get import GetAssetV2AssetsAssetIdGet
from versify.paths.v2_assets_asset_id.get import GetAssetV2AssetsAssetIdGet0
from versify.paths.v2_assets.get import ListAssetsV2AssetsGet
from versify.paths.v2_assets.get import ListAssetsV2AssetsGet0
from versify.paths.v2_assets_search.post import SearchAssetsV2AssetsSearchPost
from versify.paths.v2_assets_search.post import SearchAssetsV2AssetsSearchPost0
from versify.paths.v2_assets_asset_id.put import UpdateAssetV2AssetsAssetIdPut
from versify.paths.v2_assets_asset_id.put import UpdateAssetV2AssetsAssetIdPut0


class AssetsApi(
    CreateAssetV2AssetsPost,
    CreateAssetV2AssetsPost0,
    DeleteAssetV2AssetsAssetIdDelete,
    DeleteAssetV2AssetsAssetIdDelete0,
    GetAssetV2AssetsAssetIdGet,
    GetAssetV2AssetsAssetIdGet0,
    ListAssetsV2AssetsGet,
    ListAssetsV2AssetsGet0,
    SearchAssetsV2AssetsSearchPost,
    SearchAssetsV2AssetsSearchPost0,
    UpdateAssetV2AssetsAssetIdPut,
    UpdateAssetV2AssetsAssetIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
