# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_oauth_access_token.post import AccessTokenV2OauthAccessTokenPost
from versify.paths.v2_oauth_access_token.post import AccessTokenV2OauthAccessTokenPost0
from versify.paths.v2_auth_authenticate.post import AuthenticateV2AuthAuthenticatePost
from versify.paths.v2_auth_authenticate.post import AuthenticateV2AuthAuthenticatePost0
from versify.paths.v2_oauth_authorize.get import AuthorizeV2OauthAuthorizeGet
from versify.paths.v2_oauth_authorize.get import AuthorizeV2OauthAuthorizeGet0
from versify.paths.v2_users_me.get import GetCurrentUserV2UsersMeGet
from versify.paths.v2_oauth_user_info.get import GetUserInfoV2OauthUserInfoGet
from versify.paths.v2_auth_login.post import LoginV2AuthLoginPost
from versify.paths.v2_auth_login.post import LoginV2AuthLoginPost0
from versify.paths.v2_auth_register.post import RegisterV2AuthRegisterPost
from versify.paths.v2_auth_register.post import RegisterV2AuthRegisterPost0
from versify.paths.v2_users_me.put import UpdateCurrentUserV2UsersMePut


class AuthApi(
    AccessTokenV2OauthAccessTokenPost,
    AccessTokenV2OauthAccessTokenPost0,
    AuthenticateV2AuthAuthenticatePost,
    AuthenticateV2AuthAuthenticatePost0,
    AuthorizeV2OauthAuthorizeGet,
    AuthorizeV2OauthAuthorizeGet0,
    GetCurrentUserV2UsersMeGet,
    GetUserInfoV2OauthUserInfoGet,
    LoginV2AuthLoginPost,
    LoginV2AuthLoginPost0,
    RegisterV2AuthRegisterPost,
    RegisterV2AuthRegisterPost0,
    UpdateCurrentUserV2UsersMePut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
