# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_oauth_access_token.post import AccessTokenV2OauthAccessTokenPost
from versify.paths.v2_oauth_access_token.post import AccessTokenV2OauthAccessTokenPost0
from versify.paths.v2_oauth_authorize.get import AuthorizeV2OauthAuthorizeGet
from versify.paths.v2_oauth_authorize.get import AuthorizeV2OauthAuthorizeGet0


class AuthApi(
    AccessTokenV2OauthAccessTokenPost,
    AccessTokenV2OauthAccessTokenPost0,
    AuthorizeV2OauthAuthorizeGet,
    AuthorizeV2OauthAuthorizeGet0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
