# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_claims.post import CreateClaimV2ClaimsPost
from versify.paths.v2_claims.post import CreateClaimV2ClaimsPost0
from versify.paths.v2_claims_claim_id.delete import DeleteClaimV2ClaimsClaimIdDelete
from versify.paths.v2_claims_claim_id.delete import DeleteClaimV2ClaimsClaimIdDelete0
from versify.paths.v2_claims_claim_id.get import GetClaimV2ClaimsClaimIdGet
from versify.paths.v2_claims_claim_id.get import GetClaimV2ClaimsClaimIdGet0
from versify.paths.v2_claims.get import ListClaimsV2ClaimsGet
from versify.paths.v2_claims.get import ListClaimsV2ClaimsGet0
from versify.paths.v2_claims_search.post import SearchClaimsV2ClaimsSearchPost
from versify.paths.v2_claims_search.post import SearchClaimsV2ClaimsSearchPost0
from versify.paths.v2_claims_claim_id.put import UpdateClaimV2ClaimsClaimIdPut
from versify.paths.v2_claims_claim_id.put import UpdateClaimV2ClaimsClaimIdPut0


class ClaimsApi(
    CreateClaimV2ClaimsPost,
    CreateClaimV2ClaimsPost0,
    DeleteClaimV2ClaimsClaimIdDelete,
    DeleteClaimV2ClaimsClaimIdDelete0,
    GetClaimV2ClaimsClaimIdGet,
    GetClaimV2ClaimsClaimIdGet0,
    ListClaimsV2ClaimsGet,
    ListClaimsV2ClaimsGet0,
    SearchClaimsV2ClaimsSearchPost,
    SearchClaimsV2ClaimsSearchPost0,
    UpdateClaimV2ClaimsClaimIdPut,
    UpdateClaimV2ClaimsClaimIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
