# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_contacts.post import CreateContactV2ContactsPost
from versify.paths.v2_contacts.post import CreateContactV2ContactsPost0
from versify.paths.v2_contacts_contact_id.delete import DeleteContactV2ContactsContactIdDelete
from versify.paths.v2_contacts_contact_id.delete import DeleteContactV2ContactsContactIdDelete0
from versify.paths.v2_contacts_contact_id.get import GetContactV2ContactsContactIdGet
from versify.paths.v2_contacts_contact_id.get import GetContactV2ContactsContactIdGet0
from versify.paths.v2_contacts.get import ListContactsV2ContactsGet
from versify.paths.v2_contacts.get import ListContactsV2ContactsGet0
from versify.paths.v2_contacts_search.post import SearchContactsV2ContactsSearchPost
from versify.paths.v2_contacts_search.post import SearchContactsV2ContactsSearchPost0
from versify.paths.v2_contacts_contact_id.put import UpdateContactV2ContactsContactIdPut
from versify.paths.v2_contacts_contact_id.put import UpdateContactV2ContactsContactIdPut0


class ContactsApi(
    CreateContactV2ContactsPost,
    CreateContactV2ContactsPost0,
    DeleteContactV2ContactsContactIdDelete,
    DeleteContactV2ContactsContactIdDelete0,
    GetContactV2ContactsContactIdGet,
    GetContactV2ContactsContactIdGet0,
    ListContactsV2ContactsGet,
    ListContactsV2ContactsGet0,
    SearchContactsV2ContactsSearchPost,
    SearchContactsV2ContactsSearchPost0,
    UpdateContactV2ContactsContactIdPut,
    UpdateContactV2ContactsContactIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
