# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_messages.post import CreateMessageV2MessagesPost
from versify.paths.v2_messages.post import CreateMessageV2MessagesPost0
from versify.paths.v2_messages_message_id.delete import DeleteMessageV2MessagesMessageIdDelete
from versify.paths.v2_messages_message_id.delete import DeleteMessageV2MessagesMessageIdDelete0
from versify.paths.v2_messages_message_id.get import GetMessageV2MessagesMessageIdGet
from versify.paths.v2_messages_message_id.get import GetMessageV2MessagesMessageIdGet0
from versify.paths.v2_messages.get import ListMessagesV2MessagesGet
from versify.paths.v2_messages.get import ListMessagesV2MessagesGet0
from versify.paths.v2_messages_search.post import SearchMessagesV2MessagesSearchPost
from versify.paths.v2_messages_search.post import SearchMessagesV2MessagesSearchPost0
from versify.paths.v2_messages_message_id.put import UpdateMessageV2MessagesMessageIdPut
from versify.paths.v2_messages_message_id.put import UpdateMessageV2MessagesMessageIdPut0


class MessagesApi(
    CreateMessageV2MessagesPost,
    CreateMessageV2MessagesPost0,
    DeleteMessageV2MessagesMessageIdDelete,
    DeleteMessageV2MessagesMessageIdDelete0,
    GetMessageV2MessagesMessageIdGet,
    GetMessageV2MessagesMessageIdGet0,
    ListMessagesV2MessagesGet,
    ListMessagesV2MessagesGet0,
    SearchMessagesV2MessagesSearchPost,
    SearchMessagesV2MessagesSearchPost0,
    UpdateMessageV2MessagesMessageIdPut,
    UpdateMessageV2MessagesMessageIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
