# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_mints.post import CreateMintV2MintsPost
from versify.paths.v2_mints.post import CreateMintV2MintsPost0
from versify.paths.v2_mints_mint_id.delete import DeleteMintV2MintsMintIdDelete
from versify.paths.v2_mints_mint_id.delete import DeleteMintV2MintsMintIdDelete0
from versify.paths.v2_mints_mint_id.get import GetMintV2MintsMintIdGet
from versify.paths.v2_mints_mint_id.get import GetMintV2MintsMintIdGet0
from versify.paths.v2_mints.get import ListMintsV2MintsGet
from versify.paths.v2_mints.get import ListMintsV2MintsGet0
from versify.paths.v2_mints_search.post import SearchMintsV2MintsSearchPost
from versify.paths.v2_mints_search.post import SearchMintsV2MintsSearchPost0
from versify.paths.v2_mints_mint_id.put import UpdateMintV2MintsMintIdPut
from versify.paths.v2_mints_mint_id.put import UpdateMintV2MintsMintIdPut0


class MintsApi(
    CreateMintV2MintsPost,
    CreateMintV2MintsPost0,
    DeleteMintV2MintsMintIdDelete,
    DeleteMintV2MintsMintIdDelete0,
    GetMintV2MintsMintIdGet,
    GetMintV2MintsMintIdGet0,
    ListMintsV2MintsGet,
    ListMintsV2MintsGet0,
    SearchMintsV2MintsSearchPost,
    SearchMintsV2MintsSearchPost0,
    UpdateMintV2MintsMintIdPut,
    UpdateMintV2MintsMintIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
