# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_notes.post import CreateNoteV2NotesPost
from versify.paths.v2_notes.post import CreateNoteV2NotesPost0
from versify.paths.v2_notes_note_id.delete import DeleteNoteV2NotesNoteIdDelete
from versify.paths.v2_notes_note_id.delete import DeleteNoteV2NotesNoteIdDelete0
from versify.paths.v2_notes_note_id.get import GetNoteV2NotesNoteIdGet
from versify.paths.v2_notes_note_id.get import GetNoteV2NotesNoteIdGet0
from versify.paths.v2_notes.get import ListNotesV2NotesGet
from versify.paths.v2_notes.get import ListNotesV2NotesGet0
from versify.paths.v2_notes_search.post import SearchNotesV2NotesSearchPost
from versify.paths.v2_notes_search.post import SearchNotesV2NotesSearchPost0
from versify.paths.v2_notes_note_id.put import UpdateNoteV2NotesNoteIdPut
from versify.paths.v2_notes_note_id.put import UpdateNoteV2NotesNoteIdPut0


class NotesApi(
    CreateNoteV2NotesPost,
    CreateNoteV2NotesPost0,
    DeleteNoteV2NotesNoteIdDelete,
    DeleteNoteV2NotesNoteIdDelete0,
    GetNoteV2NotesNoteIdGet,
    GetNoteV2NotesNoteIdGet0,
    ListNotesV2NotesGet,
    ListNotesV2NotesGet0,
    SearchNotesV2NotesSearchPost,
    SearchNotesV2NotesSearchPost0,
    UpdateNoteV2NotesNoteIdPut,
    UpdateNoteV2NotesNoteIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
