# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_redemptions.post import CreateRedemptionV2RedemptionsPost
from versify.paths.v2_redemptions.post import CreateRedemptionV2RedemptionsPost0
from versify.paths.v2_redemptions_redemption_id.delete import DeleteRedemptionV2RedemptionsRedemptionIdDelete
from versify.paths.v2_redemptions_redemption_id.delete import DeleteRedemptionV2RedemptionsRedemptionIdDelete0
from versify.paths.v2_redemptions_redemption_id.get import GetRedemptionV2RedemptionsRedemptionIdGet
from versify.paths.v2_redemptions_redemption_id.get import GetRedemptionV2RedemptionsRedemptionIdGet0
from versify.paths.v2_redemptions.get import ListRedemptionsV2RedemptionsGet
from versify.paths.v2_redemptions.get import ListRedemptionsV2RedemptionsGet0
from versify.paths.v2_redemptions_search.post import SearchRedemptionsV2RedemptionsSearchPost
from versify.paths.v2_redemptions_search.post import SearchRedemptionsV2RedemptionsSearchPost0
from versify.paths.v2_redemptions_redemption_id.put import UpdateRedemptionV2RedemptionsRedemptionIdPut
from versify.paths.v2_redemptions_redemption_id.put import UpdateRedemptionV2RedemptionsRedemptionIdPut0


class RedemptionsApi(
    CreateRedemptionV2RedemptionsPost,
    CreateRedemptionV2RedemptionsPost0,
    DeleteRedemptionV2RedemptionsRedemptionIdDelete,
    DeleteRedemptionV2RedemptionsRedemptionIdDelete0,
    GetRedemptionV2RedemptionsRedemptionIdGet,
    GetRedemptionV2RedemptionsRedemptionIdGet0,
    ListRedemptionsV2RedemptionsGet,
    ListRedemptionsV2RedemptionsGet0,
    SearchRedemptionsV2RedemptionsSearchPost,
    SearchRedemptionsV2RedemptionsSearchPost0,
    UpdateRedemptionV2RedemptionsRedemptionIdPut,
    UpdateRedemptionV2RedemptionsRedemptionIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
