# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_rewards.post import CreateRewardV2RewardsPost
from versify.paths.v2_rewards.post import CreateRewardV2RewardsPost0
from versify.paths.v2_rewards_reward_id.delete import DeleteRewardV2RewardsRewardIdDelete
from versify.paths.v2_rewards_reward_id.delete import DeleteRewardV2RewardsRewardIdDelete0
from versify.paths.v2_rewards_reward_id.get import GetRewardV2RewardsRewardIdGet
from versify.paths.v2_rewards_reward_id.get import GetRewardV2RewardsRewardIdGet0
from versify.paths.v2_rewards.get import ListRewardsV2RewardsGet
from versify.paths.v2_rewards.get import ListRewardsV2RewardsGet0
from versify.paths.v2_rewards_search.post import SearchRewardsV2RewardsSearchPost
from versify.paths.v2_rewards_search.post import SearchRewardsV2RewardsSearchPost0
from versify.paths.v2_rewards_reward_id.put import UpdateRewardV2RewardsRewardIdPut
from versify.paths.v2_rewards_reward_id.put import UpdateRewardV2RewardsRewardIdPut0


class RewardsApi(
    CreateRewardV2RewardsPost,
    CreateRewardV2RewardsPost0,
    DeleteRewardV2RewardsRewardIdDelete,
    DeleteRewardV2RewardsRewardIdDelete0,
    GetRewardV2RewardsRewardIdGet,
    GetRewardV2RewardsRewardIdGet0,
    ListRewardsV2RewardsGet,
    ListRewardsV2RewardsGet0,
    SearchRewardsV2RewardsSearchPost,
    SearchRewardsV2RewardsSearchPost0,
    UpdateRewardV2RewardsRewardIdPut,
    UpdateRewardV2RewardsRewardIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
