# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_tags.post import CreateTagV2TagsPost
from versify.paths.v2_tags.post import CreateTagV2TagsPost0
from versify.paths.v2_tags_tag_id.delete import DeleteTagV2TagsTagIdDelete
from versify.paths.v2_tags_tag_id.delete import DeleteTagV2TagsTagIdDelete0
from versify.paths.v2_tags_tag_id.get import GetTagV2TagsTagIdGet
from versify.paths.v2_tags_tag_id.get import GetTagV2TagsTagIdGet0
from versify.paths.v2_tags.get import ListTagsV2TagsGet
from versify.paths.v2_tags.get import ListTagsV2TagsGet0
from versify.paths.v2_tags_search.post import SearchTagsV2TagsSearchPost
from versify.paths.v2_tags_search.post import SearchTagsV2TagsSearchPost0
from versify.paths.v2_tags_tag_id.put import UpdateTagV2TagsTagIdPut
from versify.paths.v2_tags_tag_id.put import UpdateTagV2TagsTagIdPut0


class TagsApi(
    CreateTagV2TagsPost,
    CreateTagV2TagsPost0,
    DeleteTagV2TagsTagIdDelete,
    DeleteTagV2TagsTagIdDelete0,
    GetTagV2TagsTagIdGet,
    GetTagV2TagsTagIdGet0,
    ListTagsV2TagsGet,
    ListTagsV2TagsGet0,
    SearchTagsV2TagsSearchPost,
    SearchTagsV2TagsSearchPost0,
    UpdateTagV2TagsTagIdPut,
    UpdateTagV2TagsTagIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
