# coding: utf-8

"""
    Versify API

    Versify API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from versify.paths.v2_webhooks.post import CreateWebhookV2WebhooksPost
from versify.paths.v2_webhooks.post import CreateWebhookV2WebhooksPost0
from versify.paths.v2_webhooks_webhook_id.delete import DeleteWebhookV2WebhooksWebhookIdDelete
from versify.paths.v2_webhooks_webhook_id.delete import DeleteWebhookV2WebhooksWebhookIdDelete0
from versify.paths.v2_webhooks_webhook_id.get import GetWebhookV2WebhooksWebhookIdGet
from versify.paths.v2_webhooks_webhook_id.get import GetWebhookV2WebhooksWebhookIdGet0
from versify.paths.v2_webhooks.get import ListWebhooksV2WebhooksGet
from versify.paths.v2_webhooks.get import ListWebhooksV2WebhooksGet0
from versify.paths.v2_webhooks_search.post import SearchWebhooksV2WebhooksSearchPost
from versify.paths.v2_webhooks_search.post import SearchWebhooksV2WebhooksSearchPost0
from versify.paths.v2_webhooks_webhook_id.put import UpdateWebhookV2WebhooksWebhookIdPut
from versify.paths.v2_webhooks_webhook_id.put import UpdateWebhookV2WebhooksWebhookIdPut0


class WebhooksApi(
    CreateWebhookV2WebhooksPost,
    CreateWebhookV2WebhooksPost0,
    DeleteWebhookV2WebhooksWebhookIdDelete,
    DeleteWebhookV2WebhooksWebhookIdDelete0,
    GetWebhookV2WebhooksWebhookIdGet,
    GetWebhookV2WebhooksWebhookIdGet0,
    ListWebhooksV2WebhooksGet,
    ListWebhooksV2WebhooksGet0,
    SearchWebhooksV2WebhooksSearchPost,
    SearchWebhooksV2WebhooksSearchPost0,
    UpdateWebhookV2WebhooksWebhookIdPut,
    UpdateWebhookV2WebhooksWebhookIdPut0,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
