org: versify
app: versify
service: blockchain-service

custom:
  tableName: BlockchainServiceTable

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    restApiId: ${ssm:/versify/services/api/id}
    restApiRootResourceId: ${ssm:/versify/services/api/root/resource/id}
  environment:
    ENVIRONMENT: ${opt:stage, 'dev'}
    LOG_LEVEL: INFO
    POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    POWERTOOLS_LOGGER_LOG_EVENT: true
    POWERTOOLS_METRICS_NAMESPACE: versify
    POWERTOOLS_SERVICE_NAME: blockchain-service
    POWERTOOLS_TRACE_DISABLED: false
    SECRET_NAME: /versify/platform/secret
    TABLE_NAME: ${self:custom.tableName}
  layers:
    - ${ssm:/versify/services/versify/layer/arn}
    - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPython:11
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:BatchGetItem
      Resource:
        - "arn:aws:dynamodb:${aws:region}:*:table/${self:custom.tableName}"
        - "arn:aws:dynamodb:${aws:region}:*:table/${self:custom.tableName}/*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:${self:provider.region}:*:secret:/versify/platform/secret*"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:ListObjects
      Resource:
        - "arn:aws:s3:::cdn.versifylabs.com"
        - "arn:aws:s3:::cdn.versifylabs.com/*"
        - "arn:aws:s3:::cdn-dev.versifylabs.com"
        - "arn:aws:s3:::cdn-dev.versifylabs.com/*"
  runtime: python3.9
  timeout: 30
  tracing:
    lambda: true

functions:
  OnBlockchainTransaction:
    handler: src.subscribers.on_blockchain_transaction
    name: BlockchainService-OnBlockchainTransaction
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/event-bus/arn}
          pattern:
            source:
              - alchemy
  OnCollectionCreated:
    handler: src.subscribers.on_collection_created
    name: BlockchainService-OnCollectionCreated
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/event-bus/arn}
          pattern:
            source:
              - versify
            detail-type:
              - collection.created
  OnFulfillmentCreated:
    handler: src.subscribers.on_fulfillment_created
    name: BlockchainService-OnFulfillmentCreated
    events:
      - eventBridge:
          eventBus: ${ssm:/versify/services/event-bus/arn}
          pattern:
            source:
              - versify
            detail-type:
              - fulfillment.created

resources:
  Resources:
    BlockchainServiceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: object
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        BillingMode: PROVISIONED
        GlobalSecondaryIndexes:
          - IndexName: ByObjectByStatus
            KeySchema:
              - AttributeName: object
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TableName: ${self:custom.tableName}
    BlockchainServiceTableNameParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /versify/services/blockchain/table/name
        Type: String
        Value: !Ref BlockchainServiceTable
    BlockchainServiceTableArnParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /versify/services/blockchain/table/arn
        Type: String
        Value: !GetAtt BlockchainServiceTable.Arn
    BlockchainServiceTableStreamArnParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /versify/services/blockchain/table/stream/arn
        Type: String
        Value: !GetAtt BlockchainServiceTable.StreamArn
