# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from versify import schemas  # noqa: F401


class AccountFeatures(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The features enabled for the account.
    """


    class MetaOapg:
        
        class properties:
            journeys = schemas.BoolSchema
            mints = schemas.BoolSchema
            rewards = schemas.BoolSchema
            __annotations__ = {
                "journeys": journeys,
                "mints": mints,
                "rewards": rewards,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["journeys"]) -> MetaOapg.properties.journeys: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mints"]) -> MetaOapg.properties.mints: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rewards"]) -> MetaOapg.properties.rewards: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["journeys", "mints", "rewards", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["journeys"]) -> typing.Union[MetaOapg.properties.journeys, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mints"]) -> typing.Union[MetaOapg.properties.mints, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rewards"]) -> typing.Union[MetaOapg.properties.rewards, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["journeys", "mints", "rewards", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        journeys: typing.Union[MetaOapg.properties.journeys, bool, schemas.Unset] = schemas.unset,
        mints: typing.Union[MetaOapg.properties.mints, bool, schemas.Unset] = schemas.unset,
        rewards: typing.Union[MetaOapg.properties.rewards, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccountFeatures':
        return super().__new__(
            cls,
            *_args,
            journeys=journeys,
            mints=mints,
            rewards=rewards,
            _configuration=_configuration,
            **kwargs,
        )
