# coding: utf-8

"""
    Versify API

    Versify API documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from versify import schemas  # noqa: F401


class ActionType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "create_note": "CREATE_NOTE",
            "send_app_message": "SEND_APP_MESSAGE",
            "send_email_message": "SEND_EMAIL_MESSAGE",
            "send_reward": "SEND_REWARD",
            "tag_contact": "TAG_CONTACT",
            "match_all": "MATCH_ALL",
            "match_any": "MATCH_ANY",
            "wait": "WAIT",
        }
    
    @schemas.classproperty
    def CREATE_NOTE(cls):
        return cls("create_note")
    
    @schemas.classproperty
    def SEND_APP_MESSAGE(cls):
        return cls("send_app_message")
    
    @schemas.classproperty
    def SEND_EMAIL_MESSAGE(cls):
        return cls("send_email_message")
    
    @schemas.classproperty
    def SEND_REWARD(cls):
        return cls("send_reward")
    
    @schemas.classproperty
    def TAG_CONTACT(cls):
        return cls("tag_contact")
    
    @schemas.classproperty
    def MATCH_ALL(cls):
        return cls("match_all")
    
    @schemas.classproperty
    def MATCH_ANY(cls):
        return cls("match_any")
    
    @schemas.classproperty
    def WAIT(cls):
        return cls("wait")
