name: Generate Python Client

# Runs this action whenever there are any changes to the branch.
on:
  push:
    branches:
      - dev

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      # Checks out the entire repo.
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Generates a openapi.yaml file based on the FastAPI project.
      - name: Generate OpenAPI file
        uses: column-street/fastapi-openapi-specs-action@v1.0.0
        with:
          installDepedencies: pip install -r vongo/requirements.txt
          moduleDir: vongo.app
          fileName: main.py
          appName: app

      # Uses an external tool, openapitools-generator-action, to generate the client code.
      # The 'openapirc.json' file is the following: { "packageName": "fast", "projectName": "fast" }
      # and it lives inside the master branch of the repository. Comamnd outputs a new folder called
      # 'python-client' with the relevant client code.
      - name: Generate Python Client
        uses: triaxtec/openapitools-generator-action@v1.0.0
        with:
          generator: python
          openapi-file: openapi.yaml
          config-file: openapirc.yaml

      # Deletes every file in the folder, except '.git' and the new generated 'python-client' folder.
      # Moves all content of the 'python-client' folder to the root directory.
      - name: Clean Branch
        run: |
          # Removes all files except the .git and python-client folder.
          shopt -s extglob
          sudo rm -rf !(.|..|.git|python-client)
          # Moves all of the content of the python-client folder out, 
          # and deletes the folder.
          mv python-client/* .
          rm -rf python-client

      # Pushes the new changes into another repository.
      - name: Push to Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: "GitHub Action"
          destination-repository-name: "versify-python"
          user-email: "actions.github.com"
          target-branch: dev
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
